# Generated by Django 2.1.1 on 2018-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20181128_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='smsgeteway',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
