# Generated by Django 2.1.1 on 2018-11-22 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpages',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 22, 5, 22, 9, 520103, tzinfo=utc), null=True),
        ),
    ]
