# Generated by Django 2.1.5 on 2019-01-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'In Progress'), ('A', 'Answered'), ('H', 'On Hold'), ('C', 'Closed')], default='O', max_length=120),
        ),
    ]
