# Generated by Django 2.1.5 on 2019-01-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0003_auto_20190119_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
