# Generated by Django 2.1.5 on 2019-01-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190119_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
